# Porta dedicada para o Microsserviço de Usuários
server.port=8081

# Conexão MongoDB
spring.data.mongodb.uri=mongodb://localhost:27017/barbearia-auth-db

# Propriedades de segurança (copie as chaves do seu monolito)
app.jwt.secret=SUA_CHAVE_SECRETA
# ... outras chaves de segurança/oauth2