# Nome da aplicacao (bom para logs)
spring.application.name=barbearia-payment-service

# Porta do Servidor (Mudei para 8082 para nao bater com os outros)
server.port=8082

# Conexao com o banco (cria um banco chamado 'barbearia-pagamentos')
spring.data.mongodb.uri=mongodb://localhost:27017/barbearia-pagamentos

# Formata o JSON de data para ficar bonitinho
spring.jackson.date-format=dd-MM-yyyy HH:mm:ss